name: brosenv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - altair=5.0.1=py312h06a4308_0
  - arrow-cpp=16.1.0=hc1eb8f0_0
  - attrs=23.1.0=py312h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - blas=1.0=mkl
  - blinker=1.6.2=py312h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py312ha883a20_0
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - cachetools=5.3.3=py312h06a4308_0
  - certifi=2024.7.4=py312h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py312h06a4308_0
  - expat=2.6.2=h6a678d5_0
  - freetype=2.12.1=h4a9f257_0
  - gflags=2.2.2=h6a678d5_1
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py312h06a4308_0
  - glog=0.5.0=h6a678d5_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py312h06a4308_0
  - joblib=1.4.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jsonschema=4.19.2=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcurl=8.7.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py312h06a4308_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - mdurl=0.1.0=py312h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.8=py312h5eee18b_0
  - mkl_random=1.2.4=py312hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.8.7=py312hf827012_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.14=h5eee18b_0
  - orc=2.0.1=h2d29ad5_0
  - packaging=23.2=py312h06a4308_0
  - pandas=2.2.2=py312h526ad5a_0
  - pillow=10.4.0=py312h5eee18b_0
  - pip=24.2=py312h06a4308_0
  - plotly=5.22.0=py312he106c6f_0
  - protobuf=4.25.3=py312h12ddb61_0
  - pyarrow=16.1.0=py312h526ad5a_0
  - pydeck=0.8.0=py312h06a4308_2
  - pygments=2.15.1=py312h06a4308_1
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.4=h5148396_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - requests=2.32.3=py312h06a4308_0
  - rich=13.7.1=py312h06a4308_0
  - rpds-py=0.10.6=py312hb02cf49_0
  - s2n=1.3.27=hdbd6064_0
  - setuptools=72.1.0=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.3=py312h06a4308_0
  - tk=8.6.14=h39e8969_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=py312h06a4308_0
  - tornado=6.4.1=py312h5eee18b_0
  - typing_extensions=4.11.0=py312h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.2.2=py312h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - watchdog=4.0.1=py312h06a4308_0
  - wheel=0.43.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - cmake==3.30.2
      - dlib==19.24.6
      - face-recognition==1.3.0
      - face-recognition-models==0.3.0
      - streamlit==1.37.1
prefix: /home/sky/anaconda3/envs/brosenv
